import { apiRequest } from '../../lib/apiClient';
import type { CompleteOnboardingResult, ConnectedAccountsResult, ConnectedAccountsStatus, MeResponse, UpdateNameResult, UsernameAvailability } from './auth.types';
import { messageOf, userFromMe } from './auth.utils';
import { setCurrentUser } from './auth.session';
export async function checkUsernameAvailability(username: string, signal?: AbortSignal): Promise<UsernameAvailability> { return apiRequest<UsernameAvailability>(`/auth/username-available?username=${encodeURIComponent(username)}`, { signal }); }
export async function updateCurrentUserName(name: string): Promise<UpdateNameResult> { try { const data = await apiRequest<MeResponse>('/auth/me', { method: 'PATCH', body: { name } }); const user = userFromMe(data); setCurrentUser(user); return { status: 'success', user }; } catch (err) { return { status: 'error', message: messageOf(err) }; } }
export async function completeOnboarding(organizationName?: string): Promise<CompleteOnboardingResult> { try { const data = await apiRequest<MeResponse>('/auth/onboarding', { method: 'POST', body: { organizationName } }); const user = userFromMe(data); setCurrentUser(user); return { status: 'success', user }; } catch (err) { return { status: 'error', message: messageOf(err) }; } }
export async function getConnectedAccountsStatus(): Promise<ConnectedAccountsResult> { try { const data = await apiRequest<MeResponse & ConnectedAccountsStatus>('/auth/me'); return { status: 'success', googleLinked: data.googleLinked, hasPassword: data.hasPassword }; } catch (err) { return { status: 'error', message: messageOf(err) }; } }
export async function linkGoogleAccount(idToken: string): Promise<ConnectedAccountsResult> { try { const data = await apiRequest<MeResponse & ConnectedAccountsStatus>('/auth/google/link', { method: 'POST', body: { idToken } }); return { status: 'success', googleLinked: data.googleLinked, hasPassword: data.hasPassword }; } catch (err) { return { status: 'error', message: messageOf(err) }; } }
export async function unlinkGoogleAccount(): Promise<ConnectedAccountsResult> { try { const data = await apiRequest<MeResponse & ConnectedAccountsStatus>('/auth/google/unlink', { method: 'POST' }); return { status: 'success', googleLinked: data.googleLinked, hasPassword: data.hasPassword }; } catch (err) { return { status: 'error', message: messageOf(err) }; } }
